version: "3.7"
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
    environment:
      - APP_KEY=SomeRandomStringToAddSecurity123
      - APP_ENV=development
      - APP_DEBUG=true
      - APACHE_RUN_USER=apache-www-volume
      - APACHE_RUN_GROUP=apache-www-volume
      - UNSPLASH_ACCESS_KEY=uW8WtfCMXiNif-0jTnI2tLj0ZsdAXhAyIFsWoVuAhqI
      - UNSPLASH_SECRET_KEY=Wa3Mf8o9hsJOl4Uv5-NRhFRJ6D34noOuiu2HTaFJJWw
